{"name": "test_deletion_without_id", "status": "failed", "statusDetails": {"message": "AssertionError: Status code 400 was expected and code 404 was returned.\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test.test_CourierDelete.TestDeleteCourier object at 0x0000021F655EB150>, base_url = 'http://qa-scooter.praktikum-services.ru/api/v1/'\n\n    def test_deletion_without_id(self, base_url):\n        logger.debug(\"Testing courier deletion without ID\")\n        response = requests.delete(base_url + f\"courier/\")\n>       assert response.status_code == 400, f\"Status code 400 was expected and code {response.status_code} was returned.\"\nE       AssertionError: Status code 400 was expected and code 404 was returned.\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest\\test_CourierDelete.py:25: AssertionError"}, "attachments": [{"name": "log", "source": "87f30d86-6eea-4419-8da8-050e9ec139c7-attachment.txt", "type": "text/plain"}], "start": 1692633417421, "stop": 1692633417587, "uuid": "9adb7b8f-1fa0-4153-b21c-f0cadc6643c2", "historyId": "25d7ffea571398379f3339ab13d304ac", "testCaseId": "25d7ffea571398379f3339ab13d304ac", "fullName": "test.test_CourierDelete.TestDeleteCourier#test_deletion_without_id", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_CourierDelete"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-36NVPK8"}, {"name": "thread", "value": "8484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_CourierDelete"}]}