{"name": "test_order_acceptance_without_order_id", "status": "failed", "statusDetails": {"message": "AssertionError: Status code 400 was expected and code 404 was returned.\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test.test_OrderAcceptance.TestWithoutParameters object at 0x00000228F2D0A710>, login_courier = 215368\nbase_url = 'http://qa-scooter.praktikum-services.ru/api/v1/'\n\n    def test_order_acceptance_without_order_id(self, login_courier, base_url):\n        logger.info(\"Testing order acceptance without order ID\")\n        response = requests.put(base_url + f\"orders/accept/?courierId={login_courier}\")\n        logger.debug(f\"Status code {response.status_code} was returned and message{response.json()}\")\n>       assert response.status_code == 400, f\"Status code 400 was expected and code {response.status_code} was returned.\"\nE       AssertionError: Status code 400 was expected and code 404 was returned.\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest\\test_OrderAcceptance.py:40: AssertionError"}, "attachments": [{"name": "log", "source": "0e2a833a-545e-4ad6-b8a2-dbf42806f059-attachment.txt", "type": "text/plain"}], "start": 1692635457703, "stop": 1692635457851, "uuid": "ca6ab0ec-4100-4563-9d7b-2ee9d43806d4", "historyId": "99e3c96adae11cbe0e867b015686f75e", "testCaseId": "99e3c96adae11cbe0e867b015686f75e", "fullName": "test.test_OrderAcceptance.TestWithoutParameters#test_order_acceptance_without_order_id", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_OrderAcceptance"}, {"name": "subSuite", "value": "TestWithoutParameters"}, {"name": "host", "value": "DESKTOP-36NVPK8"}, {"name": "thread", "value": "8420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_OrderAcceptance"}]}