{"name": "test_order_acceptance_without_order_id", "status": "failed", "statusDetails": {"message": "AssertionError: Status code 400 was expected and code 404 was returned.\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test.test_OrderAcceptance.TestWithoutParameters object at 0x000001B2E7186AD0>, login_courier = 213971\nbase_url = 'http://qa-scooter.praktikum-services.ru/api/v1/'\n\n    def test_order_acceptance_without_order_id(self, login_courier, base_url):\n        response = requests.put(base_url + f\"orders/accept?courierId={login_courier}\")\n>       assert response.status_code == 400, f\"Status code 400 was expected and code {response.status_code} was returned.\"\nE       AssertionError: Status code 400 was expected and code 404 was returned.\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest\\test_OrderAcceptance.py:31: AssertionError"}, "start": 1692259627774, "stop": 1692259627956, "uuid": "abb2a92b-7cf4-4d25-9bfd-1ea05e0d813e", "historyId": "99e3c96adae11cbe0e867b015686f75e", "testCaseId": "99e3c96adae11cbe0e867b015686f75e", "fullName": "test.test_OrderAcceptance.TestWithoutParameters#test_order_acceptance_without_order_id", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_OrderAcceptance"}, {"name": "subSuite", "value": "TestWithoutParameters"}, {"name": "host", "value": "DESKTOP-36NVPK8"}, {"name": "thread", "value": "1756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_OrderAcceptance"}]}