{"name": "test_order_acceptance_without_order_id", "status": "failed", "statusDetails": {"message": "AssertionError: Status code 400 was expected and code 404 was returned.\nassert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test.test_OrderAcceptance.TestWithoutParameters object at 0x0000021F65622B90>, login_courier = 215358\nbase_url = 'http://qa-scooter.praktikum-services.ru/api/v1/'\n\n    def test_order_acceptance_without_order_id(self, login_courier, base_url):\n        response = requests.put(base_url + f\"orders/accept/?courierId={login_courier}\")\n>       assert response.status_code == 400, f\"Status code 400 was expected and code {response.status_code} was returned.\"\nE       AssertionError: Status code 400 was expected and code 404 was returned.\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntest\\test_OrderAcceptance.py:31: AssertionError"}, "start": 1692633482503, "stop": 1692633482662, "uuid": "4a1d8fcf-6ead-4ac0-a09b-66a985b2188e", "historyId": "99e3c96adae11cbe0e867b015686f75e", "testCaseId": "99e3c96adae11cbe0e867b015686f75e", "fullName": "test.test_OrderAcceptance.TestWithoutParameters#test_order_acceptance_without_order_id", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_OrderAcceptance"}, {"name": "subSuite", "value": "TestWithoutParameters"}, {"name": "host", "value": "DESKTOP-36NVPK8"}, {"name": "thread", "value": "8484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_OrderAcceptance"}]}